import assert from 'node:assert/strict'
import test from 'node:test'
import {readFile} from 'node:fs/promises'
import {transform} from 'esbuild'

const source=await readFile(new URL('../src/client/KnowledgeSurface.ts',import.meta.url),'utf8')
const {code}=await transform(source,{loader:'ts',format:'esm',target:'es2022'})
const {KnowledgeSurface}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'))
const blank={sessionId:'blank',cwd:'/fixture'},first={sessionId:'first',cwd:'/fixture'},second={sessionId:'second',cwd:'/fixture'}
function fixture(){
  const filled=new Set(['first','second']),writes=[],layout=[]
  const surface=new KnowledgeSurface({openDetails:()=>layout.push('open'),closeDetails:()=>layout.push('close')},id=>filled.has(id),value=>writes.push(value))
  return {surface,filled,writes,layout}
}

test('official sessions only open explicitly, irrespective of historical preference or resizing',()=>{
  const layout=[],writes=[]
  const surface=new KnowledgeSurface({openDetails:()=>layout.push('open'),closeDetails:()=>layout.push('close')},()=>true,()=>{},()=>false)
  surface.restorePreference(true);surface.enter(blank)
  surface.enter(first);surface.restoreSidebar();surface.enter(blank)
  assert.equal(surface.getSnapshot().open,false)
  assert.deepEqual(layout,[])
  surface.toggle(blank);surface.enter(blank)
  assert.equal(surface.getSnapshot().open,true)
  assert.equal(surface.getSnapshot().reading,false)
  surface.setReading(true);surface.setReading(false)
  assert.equal(surface.getSnapshot().open,true)
  assert.equal(surface.getSnapshot().reading,false)
  assert.deepEqual(writes,[])
})

test('native session adoption preserves artifact memory without transferring reading or closing tabs',()=>{
  const {surface,layout}=fixture()
  surface.adoptTab(first,true);surface.setReading(true)
  surface.remember(first.sessionId,{artifactId:'selected-artifact'})
  surface.adoptTab(second,true)
  assert.equal(surface.getSnapshot().reading,false)
  surface.tabClosed(first.sessionId)
  assert.equal(surface.getSnapshot().sessionId,second.sessionId)
  surface.adoptTab(first,true)
  assert.equal(surface.sessionState(first.sessionId).artifactId,'selected-artifact')
  assert.deepEqual(layout,[])
})

test('official tab visibility and close clear the reader without changing preferences or another session',()=>{
  const {surface,writes,layout}=fixture()
  surface.adoptTab(first,true)
  surface.setReading(true)
  surface.adoptTab(first,false)
  assert.equal(surface.getSnapshot().reading,false)
  assert.equal(surface.getSnapshot().open,false)
  surface.adoptTab(second,true)
  surface.tabClosed(first.sessionId)
  surface.adoptTab(first,false)
  assert.equal(surface.getSnapshot().sessionId,second.sessionId)
  assert.equal(surface.getSnapshot().open,true)
  surface.tabClosed(second.sessionId)
  assert.equal(surface.getSnapshot().open,false)
  assert.deepEqual(writes,[])
  assert.deepEqual(layout,[])
})
test('fresh or historically open preferences never show an empty conversation',()=>{
  for(const open of [false,true])for(const preferenceFirst of [false,true]){
    const {surface,layout,writes}=fixture()
    if(preferenceFirst)surface.restorePreference(open)
    surface.enter(blank)
    if(!preferenceFirst)surface.restorePreference(open)
    surface.restoreSidebar()
    assert.equal(surface.getSnapshot().open,false)
    assert.ok(!surface.getSnapshot().reading)
    assert.deepEqual(layout,[])
    assert.deepEqual(writes,[])
  }
})
test('a restored preference waits for the first real conversation and opens only its sidebar',()=>{
  const {surface,filled,writes}=fixture()
  surface.enter(blank);surface.restorePreference(true)
  filled.add('blank');surface.enter(blank)
  assert.equal(surface.getSnapshot().open,true)
  assert.equal(surface.getSnapshot().reading,false)
  surface.setDetailsCollapsed(false)
  assert.deepEqual(writes,[])
})
test('an explicit blank-page opening works, survives same-session sync and return saves closed',()=>{
  const {surface,writes}=fixture()
  surface.enter(blank);surface.toggle(blank)
  surface.enter(blank)
  assert.equal(surface.getSnapshot().open,true)
  assert.equal(surface.getSnapshot().reading,true)
  surface.setReading(false)
  assert.equal(surface.getSnapshot().open,false)
  assert.equal(surface.getSnapshot().reading,false)
  assert.deepEqual(writes,[true,false])
  surface.enter(first)
  assert.equal(surface.getSnapshot().open,false)
})
test('reading does not transfer to another conversation or return when revisiting it',()=>{
  const {surface}=fixture()
  surface.enter(first);surface.toggle(first);surface.setReading(true)
  surface.remember('first',{query:'retained query',artifactId:'retained-artifact'})
  surface.enter(second)
  assert.equal(surface.getSnapshot().sessionId,'second')
  assert.equal(surface.getSnapshot().reading,false)
  surface.enter(first)
  assert.equal(surface.getSnapshot().reading,false)
  assert.deepEqual(surface.sessionState('first'),{query:'retained query',artifactId:'retained-artifact'})
  surface.enter(blank)
  assert.equal(surface.getSnapshot().open,false)
  assert.equal(surface.getSnapshot().reading,false)
})
test('closing and reopening a reader starts in the sidebar when that sidebar is usable',()=>{
  const {surface,writes}=fixture()
  surface.toggle(first);surface.setDetailsCollapsed(false);surface.setReading(true)
  surface.toggle(first);surface.toggle(first)
  assert.equal(surface.getSnapshot().open,true)
  assert.equal(surface.getSnapshot().reading,false)
  assert.deepEqual(writes,[true,false,true])
})
test('a narrow restored sidebar stays closed without overwriting the preference and restores after widening',()=>{
  const {surface,writes}=fixture()
  surface.setDetailsCollapsed(true)
  surface.enter(first);surface.restorePreference(true)
  surface.setDetailsCollapsed(true)
  assert.equal(surface.getSnapshot().open,false)
  assert.equal(surface.getSnapshot().reading,false)
  assert.deepEqual(writes,[])
  surface.restoreSidebar();surface.setDetailsCollapsed(false)
  assert.equal(surface.getSnapshot().open,true)
  assert.equal(surface.getSnapshot().reading,false)
})
test('narrow explicit opening can use the reader and returning closes its persisted preference',()=>{
  const {surface,writes}=fixture()
  surface.setDetailsCollapsed(true)
  surface.enter(first);surface.toggle(first);surface.setDetailsCollapsed(true)
  assert.equal(surface.getSnapshot().reading,true)
  surface.setReading(false)
  assert.equal(surface.getSnapshot().open,false)
  assert.deepEqual(writes,[true,false])
})
test('returning from a wide explicit reader preserves the visible sidebar and its open preference',()=>{
  const {surface,writes}=fixture()
  surface.enter(first);surface.toggle(first);surface.setDetailsCollapsed(false)
  surface.setReading(true);surface.setReading(false)
  assert.equal(surface.getSnapshot().open,true)
  assert.equal(surface.getSnapshot().reading,false)
  assert.deepEqual(writes,[true])
})
test('late preference hydration cannot override an explicit close and programmatic display does not save open',()=>{
  const {surface,writes}=fixture()
  surface.enter(first);surface.toggle(first);surface.dismiss()
  surface.restorePreference(true);surface.enter(second)
  assert.equal(surface.getSnapshot().open,false)
  surface.open(blank)
  assert.equal(surface.getSnapshot().reading,true)
  assert.deepEqual(writes,[true,false])
})
