import {StudioIcon,primaryFormats} from './StudioIcon'
import React,{useRef,useEffect} from 'react'
const b:React.CSSProperties={border:'1px solid var(--dsw-alias-border-l2, #ded7cf)',borderRadius:8,background:'transparent',padding:'7px 10px',font:'inherit',fontSize:12,color:'inherit',cursor:'pointer'}
export function WorkspaceHome({workspace,error,refresh,invoke,openArtifact,close,scrollPositions={},rememberScroll=()=>{}}:any) {
  const scrollRef=useRef<HTMLDivElement>(null)
  useEffect(()=>{if(scrollRef.current)scrollRef.current.scrollTop=scrollPositions.home||0},[])
  return <section data-knowledge-studio-details="true" style={{height:'100%',minHeight:0,display:'flex',flexDirection:'column',background:'var(--dsw-alias-bg-base, #fffdf9)',color:'var(--dsw-alias-label-primary, #302b28)',fontSize:13}}>
    <header style={{display:'flex',alignItems:'center',gap:9,padding:15,borderBottom:'1px solid var(--dsw-alias-border-l2, #e6dfd6)'}}><strong style={{fontSize:16}}>Studio</strong><span style={{fontSize:11,color:'var(--dsw-alias-label-secondary, #857a6d)',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{workspace.title}</span><button style={{...b,marginLeft:'auto',border:0}} aria-label="关闭面板" onClick={close}>×</button></header>
    <div ref={scrollRef} onScroll={e=>rememberScroll('home',e.currentTarget.scrollTop)} style={{overflowY:'auto',padding:16,flex:1}}>
      {error&&<p role="alert" style={{color:'var(--dsw-alias-state-error-primary, #ad333f)'}}>{error} <button style={b} onClick={refresh}>重试</button></p>}
        <div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:9}}>{workspace.capabilities.filter((c:any)=>c.available||c.unavailableReason).map((c:any)=><button key={c.id} disabled={!c.available} data-knowledge-studio-capability={c.id} style={{...b,textAlign:'left',padding:'14px 12px',minHeight:100,cursor:c.available?'pointer':'default',background:'var(--dsw-alias-bg-layer-2, #f7f3ed)'}} onClick={()=>invoke(c)}><span style={{display:'flex',alignItems:'center',gap:8}}><StudioIcon kind={c.id} size={22} tile/><strong style={{fontSize:14}}>{c.title}</strong></span><span style={{display:'block',fontSize:11,color:'var(--dsw-alias-label-secondary, #84776a)',lineHeight:1.5,marginTop:6}}>{c.unavailableReason||c.description}</span></button>)}</div>
        {[{label:'进行中',items:(workspace.artifacts||[]).filter((item:any)=>item.status==='running'||item.status==='queued')},{label:'最近成果',items:(workspace.artifacts||[]).filter((item:any)=>item.status!=='running'&&item.status!=='queued')}].filter(group=>group.label==='最近成果'||group.items.length).map(group=><div key={group.label} data-studio-result-group={group.label}>
          <div style={{display:'flex',alignItems:'center',marginTop:26,marginBottom:10}}><strong>{group.label}</strong><span style={{marginLeft:'auto',fontSize:11,color:'var(--dsw-alias-label-secondary, #857a6d)'}}>{group.items.length} 项</span></div>
          {!group.items.length&&<p style={{color:'var(--dsw-alias-label-secondary, #857a6d)',fontSize:12}}>选择一种形式开始，完成的成果会保存在这里。</p>}
        {group.items.map((item:any)=><button key={item.id} data-studio-artifact-id={item.id} style={{...b,width:'100%',textAlign:'left',border:0,borderBottom:'1px solid var(--dsw-alias-border-l2, #ece6de)',borderRadius:0,padding:'12px 0',display:'flex',alignItems:'center',gap:10}} onClick={()=>openArtifact(item.id)}><StudioIcon kind={item.kind} tile/><span style={{minWidth:0,flex:1}}><strong style={{display:'block',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{item.title}</strong><span style={{fontSize:11,color:'var(--dsw-alias-label-secondary, #857a6d)'}}>{workspace.capabilities.find((c:any)=>c.id===item.kind)?.title||item.kind}{primaryFormats[item.kind]?' · '+primaryFormats[item.kind].toUpperCase():''} · {item.status==='completed'?new Date(item.updatedAt).toLocaleString():item.status==='running'?'生成中':item.status==='cancelled'?'已取消':'未完成'}</span></span></button>)}
        </div>)}
    </div>
  </section>
}
